version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: terraform
    directory: /infra/aws
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: terraform
    directory: /infra/gcp
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
